# Generated by Django 3.1.4 on 2021-01-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyserverapi', '0007_auto_20210103_2238'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='image',
            field=models.ImageField(default='avatar.jpg', upload_to='images/avatars'),
        ),
    ]
