# Generated by Django 3.1.4 on 2021-01-04 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyserverapi', '0008_member_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='image',
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(default='avatar.jpg', upload_to='images/avatars'),
        ),
    ]
