# Generated by Django 3.1.4 on 2021-01-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyserverapi', '0011_member_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(default='', upload_to='images/avatars'),
        ),
    ]
