# Generated by Django 3.1.4 on 2021-01-04 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyserverapi', '0013_auto_20210104_1651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='profile_pic',
        ),
    ]
