# Generated by Django 3.1.4 on 2021-01-04 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyserverapi', '0015_member_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='image',
        ),
    ]
