# Generated by Django 3.1.4 on 2021-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchpartyserverapi', '0016_remove_channel_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='image',
            field=models.ImageField(default='group.png', upload_to='images/channels'),
        ),
    ]
